import { MenuItem, Select, Switch } from "@mui/material";
import { FastField, FormikProps } from "formik";
import { CreateProduct } from "models/products";
import { useStylesSwitch } from "modules/adminProduct/utils/MakeStyle";

export interface MarketingProps {
  form: FormikProps<CreateProduct>;
}

export default function Marketing({ form: formik }: MarketingProps) {
  const classes = useStylesSwitch();
  return (
    <>
      <h6 className="label-title">Marketing</h6>
      <div className="row mb-4">
        <label className="col-sm-2">Open Graph meta tags</label>
        <div className="col-sm-4">
          <FastField
            name="og_tags_type"
            as={Select}
            fullWidth
            size="small"
            displayEmpty
            label={false}
          >
            <MenuItem value="0">Autogenerated</MenuItem>
            <MenuItem value="1">Custom</MenuItem>
          </FastField>
        </div>
      </div>
      {formik.values.og_tags_type === "1" && (
        <div className="row mb-4">
          <label className="col-sm-2"></label>
          <div className="col-sm-4">
            <FastField as="textarea" className="form-control" name="og_tags" />
          </div>
        </div>
      )}
      <div className="row mb-4">
        <label className="col-sm-2">Meta description</label>
        <div className="col-sm-4">
          <FastField
            name="meta_desc_type"
            as={Select}
            fullWidth
            size="small"
            label={false}
          >
            <MenuItem value="A">Autogenerated</MenuItem>
            <MenuItem value="C">Custom</MenuItem>
          </FastField>
        </div>
      </div>
      {formik.values.meta_desc_type === "C" && (
        <div className="row mb-4">
          <label className="col-sm-2"></label>
          <div className="col-sm-4">
            <FastField
              as="textarea"
              className="form-control"
              name="meta_description"
            />
          </div>
        </div>
      )}
      <div className="row mb-4">
        <label className="col-sm-2">Meta keywords</label>
        <div className="col-sm-4">
          <FastField className="form-control" name="meta_keywords" />
        </div>
      </div>
      <div className="row mb-4">
        <label className="col-sm-2">Product page title</label>
        <div className="col-sm-4">
          <FastField className="form-control" name="product_page_title" />
        </div>
      </div>
      <div className="row mb-4">
        <label className="col-sm-2">Add to Facebook product feed</label>
        <div className="col-sm-4">
          <FastField
            component={Switch}
            classes={{
              root: classes.root,
              switchBase: classes.switchBase,
              thumb: classes.thumb,
              track: classes.track,
              checked: classes.checked,
            }}
            checked={Boolean(Number(formik.values.facebook_marketing_enabled))}
            onChange={(e: any) =>
              formik.setFieldValue(
                "facebook_marketing_enabled",
                Number(e.target.checked).toString()
              )
            }
          />
        </div>
      </div>
      <div className="row mb-4">
        <label className="col-sm-2">Add to Google product feed</label>
        <div className="col-sm-4">
          <FastField
            component={Switch}
            classes={{
              root: classes.root,
              switchBase: classes.switchBase,
              thumb: classes.thumb,
              track: classes.track,
              checked: classes.checked,
            }}
            checked={Boolean(Number(formik.values.google_feed_enabled))}
            onChange={(e: any) =>
              formik.setFieldValue(
                "google_feed_enabled",
                Number(e.target.checked).toString()
              )
            }
          />
        </div>
      </div>
    </>
  );
}
